Feature/non increasing flake8 errors #42 (#67)
* lint with flake8 and check error count (seperate job)

* Set limit for flake8 errors to 440 (current)

This makes sures the pep8 non-compliance doesn't go up, measured by
absolute number of violations. This contributes to solving #42 and is
related to PR #45.

Additional changes are required to bring down the number (And adjust
the limit).

* print number of errors and limit when not failing flake8

diff --git a/.github/workflows/pythonpackage.yml b/.github/workflows/pythonpackage.yml
--- a/.github/workflows/pythonpackage.yml
+++ b/.github/workflows/pythonpackage.yml
@@ -6,6 +6,33 @@ on:
       - 'README.md'
       - 'LICENCE'
 jobs:
+  lint:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v1
+    - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v1
+      with:
+        python-version: 3.7
+    - name: Install flake8
+      run: pip install flake8
+    - name: Check for syntax errors or undefined names
+      run: |
+        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
+    - name: Lint with flake8
+      run: |
+        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
+        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127
+    - name: Check that number of pep8 violations is not going up
+      run: |
+        # test that number of violations does not increase
+        FLAKE8_ERROR_CNT=$(flake8 . -qq --count --exit-zero --max-complexity=10 --max-line-length=127)
+        FLAKE8_ERROR_LIMIT=440
+        if [ "$FLAKE8_ERROR_CNT" -gt "$FLAKE8_ERROR_LIMIT" ] ; then
+            echo "Failed because the number of errors from flake8 increased (This: $FLAKE8_ERROR_CNT Previously: $FLAKE8_ERROR_LIMIT)" 1>&2
+            false
+        fi
+        echo "Number of validation errors from flake8 is: $FLAKE8_ERROR_CNT (Limit is: $FLAKE8_ERROR_LIMIT)"
   test:
     runs-on: ${{ matrix.os }}
     strategy:
@@ -25,13 +52,6 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
-    - name: Lint with flake8
-      run: |
-        pip install flake8
-        # stop the build if there are Python syntax errors or undefined names
-        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
     - name: Test with pytest
       env:
         MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
